package org.tribetalk.fln.pipeline

import org.junit.Assert.*
import org.junit.Test
import org.tribetalk.fln.model.FlnGrade
import org.tribetalk.fln.model.WorksheetDifficulty

class ActivityValidatorTest {

    @Test
    fun testClampingQuantityForBalvatika() {
        val ir = ActivityIR(
            id = "test_1",
            nipunCompetencyCode = "N-BAL.1",
            actionType = ActivityActionType.COUNT_AND_SELECT,
            grade = FlnGrade.BALVATIKA,
            primaryObjectKey = "mango",
            quantity = 15, // Exceeds Balvatika limit (10)
            correctValue = "15",
            distractorOptions = listOf("10", "12", "15")
        )

        val result = ActivityValidator.validateAndRepair(ir)
        assertFalse("Should report issue for over-limit quantity", result.isValid)
        assertEquals("Quantity should be clamped to 10 for Balvatika", 10, result.repairedIR.quantity)
        assertEquals("Correct value should be updated to match clamped quantity", "10", result.repairedIR.correctValue)
        assertTrue("Options must contain the repaired correct value", result.repairedIR.distractorOptions.contains("10"))
    }

    @Test
    fun testAutoRepairDistractorOptions() {
        val ir = ActivityIR(
            id = "test_2",
            nipunCompetencyCode = "N-G1.1",
            actionType = ActivityActionType.COUNT_AND_SELECT,
            grade = FlnGrade.GRADE_1,
            primaryObjectKey = "clay_pot",
            quantity = 7,
            correctValue = "7",
            distractorOptions = listOf("4", "5", "6") // Missing correct answer '7'!
        )

        val result = ActivityValidator.validateAndRepair(ir)
        assertTrue("Distractor options must now include the correct answer 7", result.repairedIR.distractorOptions.contains("7"))
        assertEquals("Must have at least 3 unique options", 4, result.repairedIR.distractorOptions.size)
        assertEquals("All options must be distinct", result.repairedIR.distractorOptions.distinct().size, result.repairedIR.distractorOptions.size)
    }

    @Test
    fun testConcreteAdditionValidation() {
        val ir = ActivityIR(
            id = "test_add",
            nipunCompetencyCode = "N-G1.3",
            actionType = ActivityActionType.ADDITION_CONCRETE,
            grade = FlnGrade.GRADE_1,
            primaryObjectKey = "sal_leaf",
            quantity = 3,
            secondaryQuantity = 4,
            correctValue = "99" // Flawed sum generated by curriculum planner!
        )

        val result = ActivityValidator.validateAndRepair(ir)
        assertEquals("Sum must be corrected to 3 + 4 = 7", "7", result.repairedIR.correctValue)
        assertTrue("Options must contain sum 7", result.repairedIR.distractorOptions.contains("7"))
    }

    @Test
    fun testLearnerProgressionAdvancement() {
        var state = LearnerState(
            learnerId = "child_01",
            currentTier = LinguisticTier.CORE_VOCABULARY
        )

        val activity = ActivityIR(
            id = "act_mango",
            nipunCompetencyCode = "L-G1.1",
            actionType = ActivityActionType.PICTURE_WORD_MATCH,
            primaryObjectKey = "mango",
            correctValue = "ᱩᱞ"
        )

        // 1st success
        state = LearnerProgressionEngine.recordActivityCompletion(state, activity, isSuccess = true)
        assertEquals(1, state.consecutiveSuccessStreak)
        assertEquals(LinguisticTier.CORE_VOCABULARY, state.currentTier)

        // 2nd success -> triggers progression to DESCRIPTIVE_PHRASE!
        state = LearnerProgressionEngine.recordActivityCompletion(state, activity, isSuccess = true)
        assertEquals(LinguisticTier.DESCRIPTIVE_PHRASE, state.currentTier)

        // Generate next phrase activity for mango
        val nextActivity = LearnerProgressionEngine.generateNextPhraseActivity("mango", targetTier = state.currentTier)
        assertEquals(LinguisticTier.DESCRIPTIVE_PHRASE, nextActivity.linguisticTier)
        assertEquals("ᱦᱮᱲᱮᱢ ᱩᱞ", nextActivity.correctValue)
        assertEquals("Sweet Mango", nextActivity.phraseEnglishGloss)
        assertTrue("Distractor options must contain phrase", nextActivity.distractorOptions.contains("ᱦᱮᱲᱮᱢ ᱩᱞ"))
    }
}
